---
version: "1"
registries: {}
services:
  postgresql:
    image: postgres:9.4
    expose:
      - "5432"
    volumes:
      - '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'foreman'
      POSTGRES_PASSWORD: 'foreman'
      POSTGRES_DB: 'foreman'
  foreman:
    image: centos:7
    expose:
      - "80"
    links:
      - postgresql
    hostname: foreman.example.com
    command: '/usr/sbin/httpd -D FOREGROUND'
    extra_hosts:
      - "war.eagle:172.17.0.1"
